### ISSUE TITLE
test_y2038/test_n2038 elocation error

### ISSUE THREAD

**Issue by MarkWang0304** [lmajewski/meta-y2038#1]
y2038arm login: root
root@y2038arm:~# test_y2038
test_y2038: relocation error: /opt/lib/libc.so.6: symbol _dl_fatal_printf version GLIBC_PRIVATE not defined in file ld-linux-armhf.so.3 with link time reference

root@y2038arm:~# test_n2038 
test_n2038: relocation error: /opt/lib/libc.so.6: symbol _dl_fatal_printf version GLIBC_PRIVATE not defined in file ld-linux-armhf.so.3 with link time reference

**Comment by lmajewski** [comment]
Hi Mark,

I've updated the meta-y2038 layer.

Please also adjust: meta-y2038/recipes-y2038/y2038-glibc/y2038-glibc_git.bb
to use y2038_edge branch from: 
https://github.com/lmajewski/y2038_glibc/commits/y2038_edge

Please also update:
meta-y2038/recipes-y2038/y2038-tests/y2038-tests_git.bb
to have SRCREV pointing to newest SHA1 on -master branch

**Comment by MarkWang0304** [comment]
> 
> 
> Hi Mark,
> 
> I've updated the meta-y2038 layer.
> 
> Please also adjust: meta-y2038/recipes-y2038/y2038-glibc/y2038-glibc_git.bb
> to use y2038_edge branch from:
> https://github.com/lmajewski/y2038_glibc/commits/y2038_edge
> 
> Please also update:
> meta-y2038/recipes-y2038/y2038-tests/y2038-tests_git.bb
> to have SRCREV pointing to newest SHA1 on -master branch

Hi Łukasz,

Thank you for your quick reply!
OK, got it. I'll try. Thank you!
